baseURL: https://example.com
languageCode: en-us
title: Leonard Henckel
theme: hugo-theme-cactus
copyright: 
disqusShortname: example
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Research
      url: /research
      weight: 2
    - name: Talks
      url: /talks
      weight: 3
    - name: Teaching
      url: /teaching
      weight: 4
markup:
  highlight:
    codeFences: yes
    guessSyntax: no
    hl_Lines: ''
    lineNoStart: 1
    lineNos: yes
    lineNumbersInTable: no
    noClasses: yes
    style: dracula
    tabWidth: 4
  tableOfContents:
    endLevel: 4
    ordered: no
    startLevel: 2
params:
  colortheme: white
  comments:
    cactuscomments:
      siteName: your_cactus_comments_sitename
    enabled: yes
    engine: cactus_comments
    utterances:
      label: hugo-site-name
      repo: <github_username>/<github_reponame>
      theme: github-light
  dateFormat: '2006-01-02'
  description: "Hi. I am Leonard. \n\n I am a postdoc at Copenhagen Causality Lab of KU working with Jonas Peters. \n\n
  My research focuses on how to estimate causal effects from observational data using graphical models. \n\n
  My PhD advisor was Marloes H. Maathuis at the Seminare for Statistics, ETH Zurich. \n\n
  Here is my [CV](https://drive.google.com/file/d/168IWBJP8k-8eU-OIGMA4C7Jwa9cVzGeJ/view?usp=sharing)." 
  googleAnalyticsAsync: yes
  # mainSection: 
  postsOnHomePage: 0
  projectsUrl: https://github.com/gohugoio
  rss: yes
  show_updated: yes
  showAllPostsArchive: no
  showAllPostsOnHomePage: no
  showProjectsList: no
  showReadTime: no
  social:
    - link: https://github.com/henckell
      name: github
    - link: https://scholar.google.com/citations?hl=en&user=WAxdnTIAAAAJ
      name: googlescholar
    - link: henckel@math.ku.dk
      name: email
  tagsOverview: no
